### ISSUE TITLE
CExporter no longer generates C header files?

### ISSUE THREAD

**Issue by mistahmikey** [aers/FFXIVClientStructs#1126]
Built this using VS 2022, ran it, it seemed to have no errors, but I am not seeing the C header files in the ida directory as was usually the case in the past.  Is this no longer supported?

**Comment by wolfcomp** [comment]
No it no longer exports .h files, and hasn't done so since 23rd of April.

This is due to the .h format didn't allow for parsing through the IDA/Ghidra database for renaming and setting types on functions that were already discovered. It now exports in YML format that is agnostic between both programs, so there is only one file needed.
