### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Caraxi** [aers/FFXIVClientStructs#308]
With 603b2116b6f7dc4d476ecb49d0f90b7a45fd6c47 I added versioning to Client Structs, but I failed to realize GitVersion fails to work with detached heads which makes building anything that isn't fully updated with Client Structs fails to build.

I'd like to keep versioning as I believe it will be helpful, but I'm unsure of a better way to do it.

Any ideas?

**Comment by goaaats** [comment]
This basically makes it impossible to build CS as a submodule, since submodules are always detached heads. Would be nice to add a workaround at least, until you end up finding a better solution.

Versioning would be nice, but I think having to switch to a branch manually for building is probably a no-go.

**Comment by Caraxi** [comment]
I've implemented a new system that will hopefully work better for our use case `VersionGenerator`. Please let me know if any issues are experienced

**Comment by aers** [comment]
Sorry I've been gone for a bit since I got sick and then couldn't make myself think about code for a while.

I assume you just did the same thing that https://github.com/Elskom/GitBuildInfo.SourceGenerator does
