### ISSUE TITLE
Thinking in classes instead of vtbls?

### ISSUE THREAD

**Issue by daemitus** [aers/FFXIVClientStructs#5]
What would a class-based approach look like?

Do we need to need to specify the size of a vtable at all? When I was calculating things, the only xref in a vtable is vf0. The next xref is generally the start of a new vtable. Is this the rule or just common? Do vtables continue past what look like xrefs to data (dwords, bytes, etc)? 

```
@vtbl(0x14169AE50, size=3)  # Cycle through __dict__, basically treating this like an enum
class Component__GUI__AtkResNode(Component__GUI__AtkEventTarget):
    dtor = 1  # also lose the nice layout orientation of all the addresses in a line, unless we turn off formatting, aligning the = signs. 
    ctor = 0x1404CC6B0"

@vtbl(0x14169AEC8)  # More verbose, harder to maintain? 
class Component__Gui__AtkCollisionNode(Component__GUI__AtkResNode):
    @vfunc(1)
    def dtor(): ...
    @func(0x14053F820)
    def ctor(): ...
```

It looks like a class, but its still basically working the vtables. However the automatic sizing would open up some opportunities I think. Especially if we can identify the first vtbl object regularly. Then they could all be labled something dumb like vtbl_Unknown001.

**Comment by aers** [comment]
vtbls should only be pointers to functions, and only index 0 should ever have xrefs, so yeah its possible to find the end of them automatically, unless the compiler is doing weird stuff. The xrefs are usually the ctor(s), the dtor(s), and any inlined ctors/dtors.

Btw I didn't mean Python classes. I meant we shouldnt be defining vtables, we should be defining (C++) classes/structs. This is because some classes have multiple vtbl trees due to multiple inheritance, and classes with no vfuncs have no vtbls, but still have functions that we would want to group with them logically.

`
class Client::Game::Character::BattleChara
    class Client::Game::Character::Character
        class Client::Game::Object::GameObject (vtbl 1) 0x1416C8150 (89 entries)
        class Client::Graphics::Vfx::VfxDataListenner (vtbl 2) 0x1416C8418 (2 entries)
`

both those vtbls belong to the BattleChara class, one is the vtbl for the BattleChara->Character->GameObject chain and will have all the vfuncs for those classes, the other is just the VfxDataListenner vtbl. (Unrelated but 5.4 actually added a third class that ::Character derives from, so they have 3 vtbls now).

Anyway:

- base class is responsible for defining function names for all vfuncs in their vtbl
- derived class is responsible for defining function names for vfuncs added by that derived class
- overrides can maybe be handled automatically if IDA has a script function to determine if something was already renamed by the user, otherwise we list them explicitly in derived classes (just need a number listing of functions overridden)

**Comment by aers** [comment]
```class Client::Game::Object::GameObject
    vtbl 0x1416B0EC0
        count 78 // might not need counts
        function_names
            17 EnableDraw

class Client::Graphics::Vfx::VfxDataListenner
    vtbl 0x141698960
        count 2
        function_names
            1 Something

class Client::Game::Character::Character
    vtbl 0x1416B1B48
        base Client::Game::Object::GameObject
        count 89 // this means ::Character adds 11 new functions, since GameObject already had 78
        function_overrides // vfunc overrides, 'override' keyword in C++ 
            17 // function names for the first 78 can be pulled from base class GameObject automatically
        function_names // names for added functions
            80 Something
    vtbl 0x1416B1E10
        base Client::Graphics::Vfx::VfxDataListenner 
        count 2
        function_overrides
            1, 2
    non_virtual_functions
        ctor 0x1406EA340 ```

this is all the data basically
